### ISSUE TITLE
Incomplete or missing docstrings in motion_manager

### ISSUE THREAD

**Issue by TMengi** [RoMeLaUCLA/robot-player#18]
- init has no parameter "player"
- to_player_angle_offset has no parameter "q"
- to_player_angle_offset missing parameter "angles"
- from_player_angle_offset missing parameter "angles"
- setters and getters, wait, torque_on/off, and advance_timestep have no official docstrings, just comments

**Comment by danielasun** [comment]
Let's just leave the

setters and getters, wait, torque_on/off, and advance_timestep have no official docstrings, just comments

alone for now.
