### ISSUE TITLE
test_single_joint.py throws an error in certain conditions

### ISSUE THREAD

**Issue by TMengi** [RoMeLaUCLA/robot-player#20]
I was able to run the vrep test_single_joint.py just fine when clicking run or debug directly in pycharm. It also works fine when I run it from my command prompt. But when I run it through the pycharm terminal, it throws the error below
```
Traceback (most recent call last):
  File "tests\test_single_joint.py", line 11, in <module>
    print(mm.get_all_joint_effort())
IOError: [Errno 0] Error
```
This is very strange behavior.

**Comment by danielasun** [comment]
Is this still an issue? If it is, feel free to reopen.
