### ISSUE TITLE
Defining a .shape for jit compilation could lead to unexpected behavior

### ISSUE THREAD

**Issue by TMengi** [RoMeLaUCLA/robot-player#24]
In order to use jit, all returned vectors must have a defined np.shape. This means that vector objects do not really exist and everything is a matrix. Where previously we would have returned a generic (3,) vector, we now have to return either a (3,1) or (1,3) column or row vector (which is actually a mattrix)

This becomes a problem because we used to be able to return a vector V = [v_x, v_y, v_z] with dimension (3,) such that V[0] == v_x

Now, this same vector would be V = [[v_x, v_y, v_z]] with dimension (1,3) such that V[0] == [v_x, v_y, v_z]. This will lead to problems down the line when we index a supposed vector expecting to get a scalar value but actually get another vector.

A possible workaround is to wrap the jit compiled functions which return generic vectors in a decorator which would reshape the return from (1,3) or (3,1) to just (3,). This would mean that no adjustments need be made to the driver code and we can continue using the functions as before.

**Comment by danielasun** [comment]
We don't use jit compilation for any of robot player any more so it's okay.
